[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
capture = { version = "0.1.0", path = "../capture" }
editor = { version = "0.1.0", path = "../editor" }
eframe = { version = "0.36.1", features = ["glow"] }
egui = "0.36.1"
encoder = { version = "0.1.0", path = "../encoder" }
global-hotkey = "0.8.0"
image = "0.25.10"
rfd = "0.17.2"
